In [1]:
from torch.utils.data.dataset import Dataset
from torchvision import transforms 
import torch
import numpy as np
from PIL import Image
from os import path

class ScenesDataset(Dataset):
    
    def __init__(self,base_path,txt_list,transform=None):
        self.base_path=base_path
        self.images = np.loadtxt(txt_list,dtype=str,delimiter=',')
        self.transform = transform
        
    def __getitem__(self, index):
        f,c = self.images[index]
        im = Image.open(path.join(self.base_path, f))
        if self.transform is not None:
            im = self.transform(im)
        
        label = int(c)
        
        return {'image' : im, 'label':label}
    
    def __len__(self):
        return len(self.images)

In [2]:
#resize normale
transform = transforms.Compose([transforms.Resize(32),transforms.ToTensor()])

dataset = ScenesDataset('DITS-full\DITS-full\DITS-detection\class\image','DITS-full\DITS-full\DITS-detection\class\classes.txt',transform=transform)
sample = dataset[10]
print(sample['image'].shape)
print(sample['label'])

torch.Size([3, 32, 32])
0


In [3]:
for i in range(len((dataset))):
    sample = dataset[i]
    print(sample['image'].shape)
    print(sample['label'])

torch.Size([3, 32, 33])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 33])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 33])
0
torch.Size([3, 32, 33])
0
torch.Size([3, 32, 33])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 33, 32])
0
torch.Size([3, 33, 32])
0
torch.Size([3, 33, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 33, 32])
0
torch.Size([3, 33, 32])
0
torch.Size([3, 33, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([3, 32, 32])
0
torch.Size([

torch.Size([3, 34, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 34])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([

torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 34])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 35])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 35, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 34, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 33])
1
torch.Size([3, 32, 32])
1
torch.Size([3, 33, 32])
1
torch.Size([3, 32, 32])
1
torch.Size([

torch.Size([3, 32, 32])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 34])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 33, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 34])
2
torch.Size([3, 32, 34])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 34])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 33])
2
torch.Size([3, 32, 35])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([3, 32, 32])
2
torch.Size([

In [4]:
print(sample['image'].shape[1])
print(sample['image'].shape[2])
print(sample['image'].sum(2).sum(1))
print(sample['image'])

32
32
tensor([200.1961, 152.2118, 111.9176])
tensor([[[0.1725, 0.1529, 0.1255,  ..., 0.1216, 0.1373, 0.1333],
         [0.2275, 0.1373, 0.1294,  ..., 0.1569, 0.2078, 0.2078],
         [0.2627, 0.1412, 0.1059,  ..., 0.1529, 0.1804, 0.1059],
         ...,
         [0.1216, 0.1294, 0.1412,  ..., 0.0745, 0.0745, 0.0824],
         [0.2275, 0.1608, 0.0980,  ..., 0.0706, 0.0667, 0.0667],
         [0.1804, 0.1451, 0.0902,  ..., 0.0784, 0.0706, 0.0784]],

        [[0.1765, 0.1608, 0.1255,  ..., 0.1333, 0.1490, 0.1373],
         [0.2353, 0.1451, 0.1294,  ..., 0.1922, 0.2353, 0.2196],
         [0.2706, 0.1451, 0.1059,  ..., 0.1882, 0.2078, 0.1216],
         ...,
         [0.1490, 0.1647, 0.1686,  ..., 0.0588, 0.0667, 0.0902],
         [0.2353, 0.1765, 0.1216,  ..., 0.0667, 0.0706, 0.0784],
         [0.1686, 0.1373, 0.0941,  ..., 0.0824, 0.0784, 0.0941]],

        [[0.0667, 0.0588, 0.0510,  ..., 0.0431, 0.0549, 0.0510],
         [0.1255, 0.0431, 0.0588,  ..., 0.0745, 0.1176, 0.1059],
         [0.1

In [5]:
dataset = ScenesDataset('DITS-full\DITS-full\DITS-detection\class\image','DITS-full\DITS-full\DITS-detection\class\classes.txt',transform=transform)

m = np.zeros(3)
s = np.zeros(3)
peso = 0
for sample in dataset:
    m+=sample['image'].sum(1).sum(1).numpy()
    peso+=sample['image'].shape[1]*sample['image'].shape[2]
    
m=m/(len(dataset)*peso)

for sample in dataset:
    s+=((sample['image']-torch.Tensor(m).view(3,1,1))**2).sum(1).sum(1).numpy()
    
s=np.sqrt(s/(len(dataset)*peso))

print("Medie",m)
print("Dev. Std.",s)

Medie [0.00035395 0.00032971 0.00032454]
Dev. Std. [0.01491929 0.01405751 0.01413518]


In [6]:
tens = torch.rand(3,3,3)
print(tens)
tens = tens.sum(2)
print(tens)
tens = tens.sum(1)
print(tens)

tensor([[[0.8529, 0.5275, 0.6846],
         [0.4888, 0.0183, 0.0495],
         [0.4172, 0.9408, 0.5111]],

        [[0.3374, 0.9321, 0.4540],
         [0.2800, 0.7689, 0.5382],
         [0.7284, 0.2332, 0.9869]],

        [[0.3312, 0.4414, 0.4323],
         [0.9614, 0.3554, 0.0609],
         [0.3361, 0.9881, 0.2917]]])
tensor([[2.0651, 0.5566, 1.8691],
        [1.7235, 1.5871, 1.9485],
        [1.2049, 1.3777, 1.6159]])
tensor([4.4907, 5.2591, 4.1985])
