In [1]:
from torch.utils.data.dataset import Dataset
from torchvision import transforms 
import torch
import numpy as np
from PIL import Image
from os import path

class ScenesDataset(Dataset):
    
    def __init__(self,base_path,txt_list,transform=None):
        self.base_path=base_path
        self.images = np.loadtxt(txt_list,dtype=str,delimiter=',')
        self.transform = transform
        
    def __getitem__(self, index):
        f,c = self.images[index]
        im = Image.open(path.join(self.base_path, f))
        if self.transform is not None:
            im = self.transform(im)
        
        label = int(c)
        
        return {'image' : im, 'label':label}
    
    def __len__(self):
        return len(self.images)

In [9]:
#resize normale
transform = transforms.Compose([transforms.Resize(16),transforms.ToTensor()])

dataset = ScenesDataset('DITS-full\DITS-full\DITS-detection\class\image','DITS-full\DITS-full\DITS-detection\class\classes.txt',transform=transform)
sample = dataset[10]
print(sample['image'].shape)
print(sample['label'])

torch.Size([3, 16, 16])
0


In [10]:
for i in range(len((dataset))):
    sample = dataset[i]
    print(sample['image'].shape)
    print(sample['label'])

torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([

torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 17])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 17])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 17])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([

torch.Size([3, 16, 16])
1
torch.Size([3, 17, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 17])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([

In [4]:
print(sample['image'].shape[1])
print(sample['image'].shape[2])
print(sample['image'].sum(2).sum(1))
print(sample['image'])

28
28
tensor([153.2588, 116.5608,  85.6863])
tensor([[[0.1725, 0.1451, 0.1137,  ..., 0.1137, 0.1451, 0.1412],
         [0.2314, 0.1294, 0.1176,  ..., 0.1490, 0.2000, 0.1922],
         [0.2431, 0.1255, 0.0980,  ..., 0.1451, 0.1765, 0.0941],
         ...,
         [0.1098, 0.1490, 0.1529,  ..., 0.0627, 0.0745, 0.0824],
         [0.2000, 0.1373, 0.0941,  ..., 0.0706, 0.0706, 0.0667],
         [0.1882, 0.1412, 0.0745,  ..., 0.0784, 0.0706, 0.0784]],

        [[0.1765, 0.1529, 0.1176,  ..., 0.1333, 0.1608, 0.1490],
         [0.2392, 0.1373, 0.1176,  ..., 0.1804, 0.2275, 0.2078],
         [0.2471, 0.1294, 0.0980,  ..., 0.1686, 0.2000, 0.1098],
         ...,
         [0.1451, 0.1843, 0.1725,  ..., 0.0627, 0.0667, 0.0902],
         [0.2078, 0.1608, 0.1098,  ..., 0.0667, 0.0667, 0.0784],
         [0.1765, 0.1373, 0.0784,  ..., 0.0824, 0.0784, 0.0902]],

        [[0.0667, 0.0549, 0.0510,  ..., 0.0392, 0.0627, 0.0588],
         [0.1294, 0.0431, 0.0627,  ..., 0.0667, 0.1098, 0.0941],
         [0.1

In [5]:
dataset = ScenesDataset('DITS-full\DITS-full\DITS-detection\class\image','DITS-full\DITS-full\DITS-detection\class\classes.txt',transform=transform)

m = np.zeros(3)
s = np.zeros(3)
peso = 0
for sample in dataset:
    m+=sample['image'].sum(1).sum(1).numpy()
    peso+=sample['image'].shape[1]*sample['image'].shape[2]
    
m=m/(len(dataset)*peso)

for sample in dataset:
    s+=((sample['image']-torch.Tensor(m).view(3,1,1))**2).sum(1).sum(1).numpy()
    
s=np.sqrt(s/(len(dataset)*peso))

print("Medie",m)
print("Dev. Std.",s)

Medie [0.00035396 0.00032973 0.00032457]
Dev. Std. [0.01489211 0.01402444 0.01410277]


In [6]:
tens = torch.rand(3,3,3)
print(tens)
tens = tens.sum(2)
print(tens)
tens = tens.sum(1)
print(tens)

tensor([[[0.4463, 0.0139, 0.8614],
         [0.8347, 0.4479, 0.5713],
         [0.0315, 0.2484, 0.9399]],

        [[0.2831, 0.4196, 0.8756],
         [0.6751, 0.9668, 0.2492],
         [0.7301, 0.1855, 0.6492]],

        [[0.0460, 0.1744, 0.3405],
         [0.2999, 0.7853, 0.3130],
         [0.5780, 0.5077, 0.1995]]])
tensor([[1.3216, 1.8539, 1.2198],
        [1.5784, 1.8911, 1.5648],
        [0.5609, 1.3983, 1.2851]])
tensor([4.3954, 5.0343, 3.2443])
