In [1]:
from torch.utils.data.dataset import Dataset
from torch.utils.data import DataLoader
from torch.utils.tensorboard import SummaryWriter
from torchvision import transforms
from torch import nn
from torch.optim import SGD
from sklearn.metrics import accuracy_score
from os.path import join
import torch
import numpy as np
from PIL import Image
from os import path

class ScenesDataset(Dataset):
    
    def __init__(self,base_path,txt_list,transform=None):
        self.base_path=base_path
        self.images = np.loadtxt(txt_list,dtype=str,delimiter=',')
        self.transform = transform
        
    def __getitem__(self, index):
        f,c = self.images[index]
        im = Image.open(path.join(self.base_path, f))
        if self.transform is not None:
            im = self.transform(im)
        
        label = int(c)
        
        return {'image' : im, 'label':label}
    
    def __len__(self):
        return len(self.images)

In [2]:
#resize normale
transform = transforms.Compose([transforms.Resize(16),transforms.ToTensor()])

dataset = ScenesDataset('DITS-full\DITS-full\DITS-detection\class\image','DITS-full\DITS-full\DITS-detection\class\classes.txt',transform=transform)
sample = dataset[10]
print(sample['image'].shape)
print(sample['label'])

torch.Size([3, 16, 16])
0


In [3]:
for i in range(len((dataset))):
    sample = dataset[i]
    print(sample['image'].shape)
    print(sample['label'])

torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([3, 16, 16])
0
torch.Size([

torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([3, 16, 16])
1
torch.Size([

torch.Size([3, 16, 16])
2
torch.Size([3, 16, 17])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 17])
2
torch.Size([3, 16, 17])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 17])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 17])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([3, 16, 16])
2
torch.Size([

In [4]:
print(sample['image'].shape[1])
print(sample['image'].shape[2])
print(sample['image'].sum(2).sum(1))
print(sample['image'])

16
16
tensor([50.0706, 38.0627, 27.9725])
tensor([[[0.1686, 0.1176, 0.1059, 0.0902, 0.0706, 0.0706, 0.1333, 0.2235,
          0.2157, 0.2000, 0.0941, 0.1020, 0.0980, 0.1137, 0.1373, 0.1686],
         [0.1765, 0.0980, 0.0902, 0.0902, 0.0784, 0.0824, 0.0980, 0.1412,
          0.1647, 0.1216, 0.0667, 0.0745, 0.0863, 0.1216, 0.1451, 0.1529],
         [0.1216, 0.0902, 0.0824, 0.0824, 0.0863, 0.0824, 0.1294, 0.1765,
          0.1098, 0.0706, 0.0510, 0.0588, 0.0667, 0.0941, 0.0941, 0.1294],
         [0.0863, 0.1176, 0.1137, 0.0902, 0.0941, 0.1020, 0.2000, 0.2549,
          0.1882, 0.0863, 0.0588, 0.0588, 0.0627, 0.0706, 0.0667, 0.0706],
         [0.0902, 0.1216, 0.1137, 0.0863, 0.1020, 0.1333, 0.2353, 0.2745,
          0.2431, 0.1373, 0.0627, 0.0549, 0.0706, 0.0745, 0.0706, 0.0667],
         [0.1137, 0.1294, 0.0980, 0.1137, 0.1608, 0.2196, 0.2824, 0.3333,
          0.2902, 0.2510, 0.0941, 0.0431, 0.0588, 0.0745, 0.0745, 0.0784],
         [0.1686, 0.1882, 0.0902, 0.0863, 0.1882, 0.2667, 0.3059

In [5]:
dataset = ScenesDataset('DITS-full\DITS-full\DITS-detection\class\image','DITS-full\DITS-full\DITS-detection\class\classes.txt',transform=transform)

m = np.zeros(3)
s = np.zeros(3)
peso = 0
for sample in dataset:
    m+=sample['image'].sum(1).sum(1).numpy()
    peso+=sample['image'].shape[1]*sample['image'].shape[2]
    
m=m/(len(dataset)*peso)

for sample in dataset:
    s+=((sample['image']-torch.Tensor(m).view(3,1,1))**2).sum(1).sum(1).numpy()
    
s=np.sqrt(s/(len(dataset)*peso))

print("Medie",m)
print("Dev. Std.",s)

Medie [0.00035388 0.00032966 0.00032453]
Dev. Std. [0.01475199 0.01385172 0.01393348]


In [6]:
tens = torch.rand(3,3,3)
print(tens)
tens = tens.sum(2)
print(tens)
tens = tens.sum(1)
print(tens)

tensor([[[0.6557, 0.3184, 0.1215],
         [0.5212, 0.8511, 0.7070],
         [0.0995, 0.7968, 0.2263]],

        [[0.7816, 0.3692, 0.8188],
         [0.2990, 0.5013, 0.2096],
         [0.0315, 0.7454, 0.5639]],

        [[0.9327, 0.1012, 0.4658],
         [0.8655, 0.2744, 0.7464],
         [0.1454, 0.5888, 0.1955]]])
tensor([[1.0956, 2.0794, 1.1226],
        [1.9696, 1.0099, 1.3407],
        [1.4997, 1.8862, 0.9296]])
tensor([4.2976, 4.3202, 4.3156])


In [7]:
class AverageValueMeter():
    def __init__(self):
        self.reset()
        
    def reset(self):
        self.sum = 0
        self.num = 0
        
    def add(self, value, num):
        self.sum += value*num
        self.num += num
        
    def value(self):
        try :
            return self.sum/ self.num
        except :
            return None

In [8]:
def train_classifier(model, train_loader, test_loader, exp_name='experiment' ,
                     lr=0.01, epochs=10, momentum=0.99, logdir='logs'):
    criterion = nn.CrossEntropyLoss()
    optimizer = SGD(model.parameters(), lr, momentum=momentum)
    #meters
    loss_meter = AverageValueMeter()
    acc_meter = AverageValueMeter()
    #writer
    writer = SummaryWriter(join(logdir, exp_name))
    #device
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model.to(device)
    #definiamo un dizionario contenente i Loader di training e test
    loader = {
        'train' : train_loader,
        'test' : test_loader
    }
    #iniziaLizziamo iL global step
    global_step = 0
    for e in range(epochs):
        #iteriamo tra due modalità: train e test
        for mode in ['train' , 'test']:
            loss_meter.reset(); acc_meter.reset()
            model.train() if mode == 'train' else model.eval()
            with torch.set_grad_enabled(mode=='train'): #abiLitiamo i gradienti SOLO in training
                for i, batch in enumerate(loader[mode]):
                    x=batch[0].to(device) #"portiamoLi sul device corretto"
                    y=batch[1].to(device)
                    output = model(x)
                    
                    #aggiorniamo iL gLobaL_step
                    #conterrà iL numero di campioni visti durante iL training
                    n = x.shape[0] #numero di elementi nel batch
                    global_step += n
                    l = criterion(output, y)
                    
                    if mode=='train' :
                        l.backward()
                        optimizer.step( )
                        optimizer.zero_grad ( )
                    
                    acc = accuracy_score(y.to('cpu '),output.to(' cpu').max(1)[1])
                    loss_meter.add(l.item(), n)
                    acc_meter.add(acc,n)
                    
                    #Loggiamo i risultati iterazione per iterazione SOLO durante iL training
                    if mode=='train' :
                        writer.add_scalar( ' loss/train ' ,loss_meter.value(), global_step=global_step)
                        writer.add_scalar( 'accuracy/train' ,acc_meter.value(), global_step=global_step)            
                #una voLta finita L 'epoca (sia nel caso di training che test, Loggiamo Le stime finali)
                writer.add_scalar( 'loss/' + mode, loss_meter.value(), global_step=global_step)
                writer.add_scalar( 'accuracy/' + mode, acc_meter.value(), global_step=global_step)
        #conserviamo i pesi del model Lo aLLa fine di un ciclo di training e test
        torch. save(model.state_dict(), '%s-%d.pth'%(exp_name,e+1))
    return model

In [9]:
class LeNetColor(nn.Module):
    def __init__ (self):
        super(LeNetColor, self).__init__()
        #ridefiniamo iL modeLLo utilizzando i moduli sequentiaL.
        #ne definiamo due: un "feature extractor", che estrae Le feature maps
        #e un "classificatore" che implementa i LiveLLy FC
        self.feature_extractor = nn.Sequential(
            nn.Conv2d(3, 18, 5), #Input: 3 x 32 x 32. Ouput: 18 x 28 x 28
            nn.MaxPool2d(2), #Input: 18 x 28 x 28. Output: 18 x 14 x 14
            nn.ReLU(),
            nn.Conv2d(18, 28, 5), #lnput 18 x 14 x 14. Output: 28 x le x le
            nn.MaxPool2d(2), #Input 28 x le x le. Output: 28 x 5 x 5
            nn.ReLU()
        )    
            
        self.classifier = nn.Sequential(
            nn.Linear(700, 360), #rnput: 28 * 5 * 5
            nn.ReLU(),
            nn.Linear(360, 252),
            nn.ReLU(),
            nn.Linear(252, 100)
        )
        
    def forward(self,x):
        #AppLichiamo Le diverse trasformazioni in cascata
        x = self.feature_extractor(x)
        x = self.classifier(x.view(x.shape[0],-1))
        return x

In [10]:
dataset_loader = DataLoader(dataset, batch_size=1024, num_workers=2, shuffle=True)
#cifar100_test_loader = DataLoader(cifar100_test, batch_size=1024, num_workers=2)

In [ ]:
lenet_dataset = LeNetColor()
lenet_dataset = train_classifier(lenet_dataset, dataset_loader, dataset_loader, \
                                 'lenet_dataset', epochs=10)